### ISSUE TITLE
void mix_word logic improvement

### ISSUE THREAD

**Issue by Devmanprime** [ankitsm08/class-12-comp-java#1]
https://github.com/ankitsm08/class-12-comp-java/blob/master/Programs%2FMix.java
Time and space can be reduced further by swapping P and Q using Mix T object and then a for loop to mix two words and then add the remaining letters of the longer word stored in Q after swapping. The Swap can be done earlier in main function.

**Comment by ankitsm08** [comment]
Thanks for the suggestion!

However, swapping P and Q in the main function doesn't really improve performance. The mix_word() method efficiently handles the mixing, and moving the logic outside does not reduce time or space complexity; it just shifts where the comparison happens. Plus, it violates encapsulation principles and increases space by creating extra Mix Object. So, I’ll stick with the current approach.

Thanks again! Closing this issue now.
