### ISSUE TITLE
Minor mistakes.

### ISSUE THREAD

**Issue by Devmanprime** [ankitsm08/class-12-comp-java#2]
https://github.com/ankitsm08/class-12-comp-java/blob/master/Programs%2FDateConvert.java
-  In project.dox, the space taken by another useless array was removed but not here.

- It could also be possible that user wants to see the date of the next year so the if condition to check if n exceeds more than a year maybe useless.

- The while(n>daysInMonths[m])
{
    n-=daysInMonths[m];
    m++;
    if(m==daysInMonth.length)
        m=0;
}
d=n;
This absorbs the useless break statement as well.

**Comment by ankitsm08** [comment]
Closing this issue as this is a copy of [issue 3](https://github.com/ankitsm08/class-12-comp-java/issues/3)
