### ISSUE TITLE
Minor mistakes

### ISSUE THREAD

**Issue by Devmanprime** [ankitsm08/class-12-comp-java#3]
https://github.com/ankitsm08/class-12-comp-java/blob/master/Programs%2FDateConvert.java
-  In project.dox, the space taken by another useless array was removed but not here.

- It could also be possible that user wants to see the date of the next year so the if condition to check if n exceeds more than a year maybe useless.

- The while(n>daysInMonths[m])
{
    n-=daysInMonths[m];
    m++;
    if(m==daysInMonth.length)
        m=0;
}
d=n;
This absorbs the useless break statement as well.

**Comment by ankitsm08** [comment]
Great Suggestions!

1. The correction is now updated in the /Programs/DateConvert.java file.
   commit: [c5c0b201d7f070134c69a130c92f23cd3ba79694](https://github.com/ankitsm08/class-12-comp-java/commit/c5c0b201d7f070134c69a130c92f23cd3ba79694)

2. The Program follows the logic as in the question, as stated in day_to_date() description.
   question: [/Questions/DateConvert.md](https://github.com/ankitsm08/class-12-comp-java/blob/master/Questions/DateConvert.md)
   
   Although, it can be removed accounting for next or previous years.
   commit: [f4db77d51044d18567c73e1346503d740ce0fcf3](https://github.com/ankitsm08/class-12-comp-java/commit/f4db77d51044d18567c73e1346503d740ce0fcf3)

3. Nice optimization. But I made the code not to change the value of n, by using temporary variable.
   Also, we ensure that n is within 1-365(6) so the if check is unnecessary.
   commit: [d859280b4cfde545d06f9805a57aab8528e3f320](https://github.com/ankitsm08/class-12-comp-java/commit/d859280b4cfde545d06f9805a57aab8528e3f320)

Thanks for the suggestions and improvements!
